version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15.3-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Unit tests
                command: yarn test:unit
            - run:
                name: Build
                command: yarn build
            # Disabled until the application gets deployed during pipeline
            #- run:
            #    name: Automated tests
            #    command: yarn test:automated
