version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15.3-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Unit tests
                command: yarn test:unit
            - run:
                name: Build
                command: yarn build && yarn package && yarn docker:build
            - run:
                name: Run docker container
                command: docker container run -dit --name test --publish 8080:80 grzegorzjudas/react-enterprise-starter && docker container logs test
            - run:
                name: Wait for the application to start
                command: wget --retry-connrefused --waitretry=3 -t 5 "http://$(hostname --ip-address):8080" > /dev/null
            - run:
                name: Automated tests
                command: yarn test:automated
            - run:
                name: Cleanup
                command: docker container rm -f test
